variables:
  AUDIT_AWS_EC2_ATK_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_EC2_ATK_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_EC2_ATK_EXPECTED_TAGS:
    description: the tag we want to see on instances
    required: true
    type: string
    default: '"EXAMPLE_TAG_1", "EXAMPLE_TAG_2"'
  AUDIT_AWS_EC2_ATK_TAG_LOGIC:
    description: '"or" or "and"'
    required: true
    type: string
    default: 'and'
  AUDIT_AWS_EC2_ATK_RECIPIENT:
    description: ""
    required: true
    type: string
    default:
  AUDIT_AWS_EC2_ATK_RECIPIENT_2:
    description: "Enter the email address(es) that will receive notifications for objects with no owner tag (Optional, only if owner tag is enabled)."
    required: true
    type: string
    default:
  AUDIT_AWS_EC2_ATK_OWNER_TAG:
    description: "Enter an AWS tag whose value is an email address of owner of the EC2_ATK object. (Optional)"
    required: false
    type: string
    default: "NOT_A_TAG"
  AUDIT_AWS_EC2_ATK_FULL_JSON_REPORT:
    description: "Would you like to send the full JSON report? Options - notify / nothing. Default is notify."
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_EC2_ATK_OWNERS_HTML_REPORT:
    description: "Would you like to send the AWS owner tag report(s)? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "notify"
  AUDIT_AWS_EC2_ATK_ROLLUP_REPORT:
    description: "Would you like to send a Summary EC2_ATK report? Options - notify / nothing. Default is no / nothing."
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_EC2_ATK_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - eu-west-1
