variables:
  AUDIT_AWS_EC2_ATK_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_EC2_ATK_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_EC2_ATK_EXPECTED_TAGS:
    description: the tag we want to see on instances
    required: true
    type: string
    default: '"EXAMPLE_TAG_1", "EXAMPLE_TAG_2"'
  AUDIT_AWS_EC2_ATK_TAG_LOGIC:
    description: '"or" or "and"'
    required: true
    type: string
    default: '"and"'
  AUDIT_AWS_EC2_ATK_ALERT_TO_KILL_ADVISE:
    description: ""
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_EC2_ATK_ALERT_TO_KILL_NOTIF:
    description: ""
    required: true
    type: string
    default: "nothing"
  AUDIT_AWS_EC2_ATK_ALERT_TO_KILL_RECIPIENT:
    description: ""
    required: false
    type: string
    default:
  AUDIT_AWS_EC2_ATK_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        - eu-west-1
  AUDIT_AWS_EC2_ATK_OWNER_TAG:
      description: "Enter an AWS tag whose value is an email address of owner of the ELB object. (Optional)"
      required: false
      type: string
      default: "NOT_A_TAG"